services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes: ["./.mongo:/data/db"]

  api:
    build: .
    ports: ["5000:5000"]
    env_file: .env
    depends_on: [mongo]
